name: Github Actions Deployment Leantime and Gatus Apps AWS

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  Deploy-Leantime:
    name: Deploy Leantime App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: leantime/task-definition.json
          service: leantime-service
          cluster: lks-oss-cluster
          wait-for-service-stability: true

  Deploy-Gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Inject Token
      - name: Inject token to config.yaml
        run: |
            sed -i "s/\${GITHUB_TOKEN}/${{ secrets.TOKEN }}/g" gatus/config/config.yaml
            sed -i "s/\${ALB_ENDPOINT}/${{ secrets.ALB_ENDPOINT }}/g" gatus/config/config.yaml

      # Build Masukan Build command ECR
      - name: Build Gatus Images
        run: docker build -t lks-gatus .
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377054079.dkr.ecr.us-east-1.amazonaws.com
      - name: Tag Gatus Image
        run: docker tag lks-gatus:latest 891377054079.dkr.ecr.us-east-1.amazonaws.com/lks-gatus:latest
      - name: Push Gatus Image to ECR
        run: docker push 891377054079.dkr.ecr.us-east-1.amazonaws.com/lks-gatus:latest
      - name: Deploy Gatus Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: gatus/task-definition.json
          service: gatus-service
          cluster: lks-oss-cluster
          wait-for-service-stability: true